kind: BuildConfig
apiVersion: apps/v1
metadata:
  name: blog-hms
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift-instruqt/blog-django-py.git'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'blog-hms:latest'
  output:
    to:
      kind: ImageStreamTag
      name: 'blog-hms-app:latest'
  triggers:
    - type: ConfigChange
    - type: ImageChange