apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-hms
  namespace: fiap-hamses-6aso
spec:
  selector:
    matchLabels:
      app: hms-blog
  replicas: 1
  template:
    metadata:
      labels:
        app: hms-blog
    spec:
      containers:
        - name: hms-blog
          image: https://github.com/openshift-instruqt/blog-django-py
          ports:
            - containerPort: 8080
