apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: fiap-hamses-6aso
spec:
  selector:
    matchLabels:
      app: hms-blog
  replicas: 3
  template:
    metadata:
      labels:
        app: hms-blog
    spec:
      containers:
        - name: hms-blog
          image: openshiftkatacoda/blog-django-py
          ports:
            - containerPort: 8080
