apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-hms
  namespace: fiap-hamses-6aso
spec:
  selector:
    matchLabels:
      app: hms-blog
  replicas: 1
  template:
    metadata:
      labels:
        app: hms-blog
    spec:
      containers:
        - name: hms-blog
          image: image-registry.openshift-image-registry.svc:5000/openshift/python@sha256:210326ea7d1a940d7e8f057cc96a6115c8443658b91a95d6c0ddc91ad80566cd
          ports:
            - containerPort: 8080