kind: ReplicaSet
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-uri: 'https://github.com/openshift-katacoda/blog-django-py.git'
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '2'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"blog-hms-py-git:latest","namespace":"fiap-hamses-6aso"},"fieldPath":"spec.template.spec.containers[?(@.name==\"blog-hms-py-git\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: >-
    /apis/apps/v1/namespaces/fiap-hamses-6aso/replicasets/blog-hms-py-git
  resourceVersion: '27524554'
  name: blog-hms-py-git
  uid: 3da3b573-ef0f-42fc-a2ee-f3c170012a8e
  creationTimestamp: '2022-01-21T23:10:28Z'
  generation: 1
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-01-21T23:10:34Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:deployment.kubernetes.io/desired-replicas': {}
            'f:deployment.kubernetes.io/max-replicas': {}
            'f:deployment.kubernetes.io/revision': {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:deploymentconfig': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"9a27e126-037c-427a-81ae-b20851a9143c"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:replicas': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
              'f:pod-template-hash': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
                'f:pod-template-hash': {}
            'f:spec':
              'f:containers':
                'k:{"name":"blog-hms-py-git"}':
                  .: {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
        'f:status':
          'f:availableReplicas': {}
          'f:fullyLabeledReplicas': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
  namespace: fiap-hamses-6aso
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: blog-hms-py-git
      uid: 9a27e126-037c-427a-81ae-b20851a8605
      controller: true
      blockOwnerDeletion: true
  labels:
    app: blog-hms-py-git
    deploymentconfig: blog-hms-py-git
    pod-template-hash: 7fc889997b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-hms-py-git
      pod-template-hash: 7fc889997b
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blog-hms-py-git
        deploymentconfig: blog-hms-py-git
        pod-template-hash: 7fc889997b
    spec:
      containers:
        - name: blog-hms-py-git
          image: >-
            image-registry.openshift-image-registry.svc:5000/fiap-hamses-6aso/blog-hms-py-git@sha256:edb3b11b7e555df1bd45d968a4a6a20ec7e98a80e234dacf37066d17c461ff48
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  replicas: 1
  fullyLabeledReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  observedGeneration: 1
