kind: Secret
apiVersion: v1
metadata:
  name: blog-hms-py-git-github-webhook-secret
  namespace: hamses-ocp-fiap
  selfLink: >-
    /api/v1/namespaces/hamses-ocp-fiap/secrets/blog-hms-py-git-github-webhook-secret
  uid: 1dae94a7-39e3-48a4-870f-2bcbaf008605
  resourceVersion: '27523770'
  creationTimestamp: '2022-01-21T23:09:22Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2022-01-21T23:09:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:WebHookSecretKey': {}
        'f:type': {}
data:
  WebHookSecretKey: YWU4OWQ2OTUwZTJiMWMzYQ==
type: Opaque