kind: Secret
apiVersion: v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  selfLink: /api/v1/namespaces/hamses-ocp-fiap/secrets/hms-database
  resourceVersion: '27636453'
  name: hms-database
  uid: f540b51b-bf9b-4be3-8ccf-ebb7e27f8605
  creationTimestamp: '2022-01-22T01:49:50Z'
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: v1
      time: '2022-01-22T01:49:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:database-name': {}
          'f:database-password': {}
          'f:database-user': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
            'f:template.openshift.io/expose-database_name': {}
            'f:template.openshift.io/expose-password': {}
            'f:template.openshift.io/expose-username': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:template': {}
        'f:type': {}
  namespace: hamses-ocp-fiap
  labels:
    app: hms-database
    app.kubernetes.io/component: hms-database
    app.kubernetes.io/instance: hms-database
    template: postgresql-persistent-template
data:
  database-name: aG1zLWRhdGFiYXNl
  database-password: aG1zZGJmaWFwQDA1
  database-user: ZGh0aHMxMDA=
type: Opaque